// EinsteinProblem.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <cassert>
#include <iostream>
#include <string.h>
#include <map>
#include <vector>
#include <set>
#include "House.h"
#include "Street.h"
#include "PuzzleSolver.h"
#include "PuzzleMaker.h"

/*
Original Rules:

The Englishman lives in the red house.
The Swede keeps dogs.
The Dane drinks tea.
The green house is just to the left of the white one.
The owner of the green house drinks coffee.
The Pall Mall smoker keeps birds.
The owner of the yellow house smokes Dunhills.
The man in the center house drinks milk.
The Norwegian lives in the first house.
The Blend smoker has a neighbor who keeps cats.
The man who smokes Blue Masters drinks bier.
The man who keeps horses lives next to the Dunhill smoker.
The German smokes Prince.
The Norwegian lives next to the blue house.
The Blend smoker has a neighbor who drinks water.
*/

// Arrays of characteristic info. Each one in a category is unique to a particular house.
string categories[] = { "address", "color", "nationality", "drink", "cigarette", "pet" };
string colors[] = { "blue", "green", "red", "white", "yellow" };
string nationalities[] = { "Danish", "English", "German", "Swedish", "Norwegian" };
string drinks[] = { "beer", "coffee", "milk", "tea", "water" };
string cigarettes[] = { "Blend", "Bluemaster", "Dunhill", "Pall Mall", "Prince" };
string pets[] = { "bird", "cat", "dog", "fish", "horse" };

// Process the informational arrays above into more useable data structures
void process_characteristics() {
    string* array_lookup[TOTAL_CATEGORIES] = { colors, nationalities, drinks, cigarettes, pets };
    for (int j = 0; j < TOTAL_CATEGORIES; j++) {
        for (int i = 0; i < TOTAL_HOUSES; i++) {
            House::add_characteristic_and_category(array_lookup[j][i], j, i);
        }
    }
}

void solve_basic_puzzle() {
#if 1
    // The original rules
    string rules[] = { "pair 'English' 'red'",
        "pair 'Swedish' 'dog'",
        "pair 'Danish' 'tea'",
        "neighbor 'green' 'white' 1",
        "pair 'green' 'coffee'",
        "pair 'Pall Mall' 'bird'",
        "pair 'yellow' 'Dunhill'",
        "address 3 'milk'",
        "address 1 'Norwegian'",
        "neighbor 'Blend' 'cat'",
        "pair 'Bluemaster' 'beer'",
        "neighbor 'horse' 'Dunhill'",
        "pair 'German' 'Prince'",
        "neighbor 'Norwegian' 'blue'",
        "neighbor 'Blend' 'water'",
        "single 'fish'",
        "done" };
#else
    // Sample autogenerated rules
    string rules[] = { "address 3 'English'",
        "pair 'red' 'Swedish'",
        "pair 'fish' 'Blend'",
        "pair 'yellow' 'coffee'",
        "address 4 'Swedish'",
        "neighbor 'dog' 'Pall Mall' 1",
        "pair 'blue' 'Danish'",
        "pair 'tea' 'cat'",
        "pair 'horse' 'coffee'",
        "neighbor 'Danish' 'Norwegian'",
        "pair 'green' 'water'",
        "neighbor 'bird' 'blue' 1",
        "pair 'water' 'German'",
        "neighbor 'bird' 'Bluemaster'",
        "pair 'Prince' 'cat'",
        "neighbor 'dog' 'milk'",
        "single 'beer'",
        "done" };
#endif

    PuzzleSolver solver;
    solver.set_verbose(true);
    solver.add_steps(rules);
    while (solver.run_next_step()) {

    }
    solver.street_group.print_street_list();
}

void make_puzzle() {
    PuzzleMaker maker;
    maker.make_model_street();
    maker.make_puzzle();
}

int main(int argc, char** argv)
{
    std::cout << "Einstein's Puzzle\n-----------------\n";
    cout << "(Use 'help' argument for help)" << endl;
    cout << "Arguments: ";
    string parm = "";
    for (int arg = 1; arg < argc; arg++) {
        cout << argv[arg] << " ";
        if (arg == 1) parm = argv[arg];
    }
    cout << endl << endl;

    process_characteristics();

    if (parm == "help") {
        cout << "Use 'basic' argument (or nothing) to solve basic puzzle. Use 'generate' argument to generate puzzle." << endl;
    }
    else if (parm == "basic" || argc == 1) {
        solve_basic_puzzle();
    }
    else if (parm == "generate") {
        make_puzzle();
    }
    else {
        cout << "Unknown argument: " << parm << endl;
    }
}

